[package]
name = "chem-policies"
version = "0.1.0"
edition = "2021"

[dependencies]
chem-core = { path = "../chem-core" }
chem-domain = { path = "../chem-domain" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
