# Ejemplo F4: Acquire→Compute
[flow]
name = "basic_acquire_compute"

[[steps]]
id = "acquire_molecules"
kind = "Source"
  [steps.params]
  dataset = "synthetic_v1"

[[steps]]
id = "compute_properties"
kind = "Transform"
  [steps.params]
  kind = "stub_v1"
